# Generated by Django 3.2.7 on 2021-09-10 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='avatar',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='avatar/foods/'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='avatar',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='avatar/restaurants/'),
        ),
    ]
