# Generated by Django 3.2.7 on 2021-09-10 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210910_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='avatar',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='pictures/foods/'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='avatar',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='pictures/restaurants/'),
        ),
    ]
