# Generated by Django 3.2.7 on 2021-09-11 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210911_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='calories',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='food',
            name='weight',
            field=models.FloatField(default=0.0),
        ),
    ]
