# Generated by Django 3.2.7 on 2021-09-10 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, to='core.RestaurantCategory'),
        ),
    ]
