# Generated by Django 3.2.7 on 2021-09-10 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_restaurant_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodcategory',
            name='restaurant',
        ),
        migrations.AddField(
            model_name='foodcategory',
            name='restaurant',
            field=models.ManyToManyField(default=0, related_name='food_categories', to='core.Restaurant'),
        ),
    ]
