# Generated by Django 3.2.7 on 2021-09-10 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210910_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodcategory',
            name='restaurant',
            field=models.ManyToManyField(related_name='food_categories', to='core.Restaurant'),
        ),
    ]
