# Generated by Django 3.2.7 on 2021-09-10 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_foodcategory_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodcategory',
            name='restaurant',
            field=models.ManyToManyField(blank=True, null=True, to='core.Restaurant'),
        ),
    ]
