# Generated by Django 3.2.7 on 2021-09-10 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_foodcategory_restaurant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodcategory',
            name='restaurant',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='category',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='food_category',
            field=models.ManyToManyField(blank=True, null=True, to='core.FoodCategory'),
        ),
        migrations.AddField(
            model_name='restaurantcategory',
            name='restaurant',
            field=models.ManyToManyField(blank=True, null=True, to='core.Restaurant'),
        ),
    ]
