# Generated by Django 3.2.7 on 2021-09-10 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20210910_1226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurantcategory',
            name='restaurant',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='restaurant_category',
            field=models.ManyToManyField(blank=True, default=0, null=True, to='core.RestaurantCategory'),
        ),
    ]
