# Generated by Django 3.2.7 on 2021-09-10 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20210910_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='restaurant_category',
            field=models.ManyToManyField(blank=True, null=True, to='core.RestaurantCategory'),
        ),
    ]
