# Generated by Django 3.2.7 on 2021-09-10 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_restaurant_restaurant_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='food_category',
            field=models.ManyToManyField(blank=True, null=True, related_name='restaurants', to='core.FoodCategory'),
        ),
    ]
