# Generated by Django 3.2.7 on 2021-09-10 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_restaurant_food_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='restaurant',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_foods', to='core.restaurant'),
        ),
        migrations.AlterField(
            model_name='food',
            name='food_category',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='category_foods', to='core.foodcategory'),
        ),
    ]
