# Generated by Django 3.2.7 on 2021-09-10 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20210910_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='food_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_foods', to='core.foodcategory'),
        ),
        migrations.AlterField(
            model_name='food',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_foods', to='core.restaurant'),
        ),
    ]
