# Generated by Django 3.2.7 on 2021-09-13 12:52

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_order_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='products',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=[], size=None),
        ),
    ]
