# Generated by Django 3.2.7 on 2021-09-14 08:01

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210911_1556'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0004_order_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookDate', models.DateField()),
                ('bookTime', models.TimeField()),
                ('participants', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=[], size=None)),
                ('peopleCount', models.IntegerField(blank=True, null=True)),
                ('table', models.IntegerField()),
                ('bookComment', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('products', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=[], size=None)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('restaurant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='core.restaurant')),
            ],
        ),
    ]
